name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: WarenGonzaga
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: Asia/Manila
          config_twemoji: yes

          # Introduction plugin
          plugin_introduction: yes
          plugin_introduction_title: yes

          # Activities plugin
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

          # Language plugin
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

          # Achievement plugin
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B

          # Notable contributions
          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_repositories: yes

          # People plugin
          plugin_people: yes
          plugin_people_limit: 150
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers

          # Isocalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
